# $HOME/devel/kopia/tools/.tools/gotestsum-1.10.0/gotestsum --debug --format=standard-verbose --no-summary=skipped --jsonfile=.tmp.unit-tests.json -- -v -tags testing -count=1 -timeout 1200s ./...
$HOME/devel/kopia/tools/.tools/gotestsum-1.10.0/gotestsum --format=pkgname-and-test-fails --no-summary=skipped --jsonfile=.tmp.unit-tests.json --  -tags testing -count=1 -timeout 1200s ./cli/...
